[versions]
targetSdk = "36"
minSdk = "24"
minSdkBaselineProfile = "28"
android-application = "9.1.0-alpha01"
compose-multiplatform = "1.11.0-alpha01"

kotlin = "2.3.0"

aboutlibraries = "13.2.1"
activity = "1.12.2"
adaptive = "1.3.0-alpha03"
test-junit = "1.3.0"
benchmark = "1.5.0-alpha01"
billing = "8.2.1"
buildkonfig = "0.17.1"
coil = "3.3.0"
composeWebview = "0.33.6"
core = "1.17.0"
core-remoteviews = "1.1.0"
coroutines = "1.10.2"
crashlytics = "3.0.6"
cryptohash = "1.0.2"
datastore = "1.3.0-alpha03"
espresso-core = "3.7.0"
firebase-bom = "34.7.0"
google-services = "4.4.4"
kermit = "2.0.8"
koalaplot = "0.10.4"
kotlinCsvJvm = "1.10.0"
ksp = "2.3.4"
ktor = "3.3.3"
lifecycle = "2.10.0-alpha07"
material3 = "1.11.0-alpha01"
media = "1.7.1"
nanohttpd = "2.3.1"
nav3 = "1.1.0-alpha01"
okhttp = "5.3.2"
paging = "3.4.0-beta01"
play-publisher = "3.13.0"
profileinstaller = "1.4.1"
qrcode = "4.5.0"
review = "2.0.2"
room = "2.8.4"
runner = "1.7.0"
serialization-json = "1.10.0-RC"
shimmer = "1.3.3"
sqlite = "2.6.2"
uiautomator = "2.4.0-alpha07"
work-runtime = "2.11.0"

[libraries]
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }
adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "adaptive" }
adaptive-nav3 = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "adaptive" }

compose-webview = { module = "io.github.kevinnzou:compose-webview", version.ref = "composeWebview" }
cryptohash = { module = "com.appmattus.crypto:cryptohash", version.ref = "cryptohash" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplot" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer" }
kotlin-csv-jvm = { module = "com.jsoizo:kotlin-csv-jvm", version.ref = "kotlinCsvJvm" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
test-runner = { module = "androidx.test:runner", version.ref = "runner" }
core-remoteviews = { module = "androidx.core:core-remoteviews", version.ref = "core-remoteviews" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }
test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "work-runtime" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
core = { module = "androidx.core:core", version.ref = "core" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-nav3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
nav3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "nav3" }
lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
media = { module = "androidx.media:media", version.ref = "media" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
qrcode = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qrcode" }
review = { module = "com.google.android.play:review", version.ref = "review" }
benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-junit" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
test = { id = "com.android.test", version.ref = "android-application" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "benchmark" }
play-publisher = { id = "com.github.triplet.play", version.ref = "play-publisher" }
android-library = { id = "com.android.library", version.ref = "android-application" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
room = { id = "androidx.room", version.ref = "room" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-application" }
[bundles]


