[versions]
aboutlibraries = "10.9.2"
androidSnowfall = "1.2.1"
annotation = "1.7.0"
bimap = "1.1.0"
coil = "2.5.0"
constraintlayout = "2.2.0-alpha13"
billing = "6.0.1"
core-ktx = "1.13.0-alpha01"
appcompat = "1.7.0-alpha03"
core-remoteviews = "1.0.0"
desugar_jdk_libs = "2.0.4"
espresso-core = "3.6.0-alpha01"
firebase-bom = "32.5.0"
crashlytics = "2.9.9"
fragment-ktx = "1.7.0-alpha06"
harmony = "1.2.4"
junit = "4.13.2"
kotlin = "1.9.20"
kotlinx-serialization-json = "1.6.0"
ktorBom = "2.3.6"
kumo-core = "1.28.1"
krate = "2.0.0"
lifecycle = "2.6.2"
live-event = "1.3.0"
material = "1.11.0-beta01"
media = "1.7.0-beta01"
mpAndroidChart = "v3.1.0"
navigation = "2.7.5"
nestedscrollwebview = "0.1.5"
okhttp = "5.0.0-alpha.11"
palette-ktx = "1.0.0"
persistentCookieJar = "v1.0.1"
play-publisher = "4.0.0-SNAPSHOT"
preference-ktx = "1.2.1"
profileinstaller = "1.3.1"
recyclerview = "1.3.2"
runner = "1.6.0-alpha04"
timber = "5.0.1"
swiperefreshlayout = "1.2.0-alpha01"
room = "2.6.0"
review-ktx = "2.0.1"
uiautomator = "2.3.0-alpha05"
vertical-stepper-form = "2.7.0"
work-runtime-ktx = "2.9.0-rc01"
google-services = "4.4.0"
android-application = "8.3.0-alpha13"
benchmark-macro-junit4 = "1.2.0"
ksp = "1.9.20-1.0.14"
github-release = "2.4.1"
baselineprofile = "1.2.0"
androidx-test-ext-junit = "1.1.5"
transition = "1.5.0-alpha04"

[libraries]
android-snowfall = { module = "com.github.jetradarmobile:android-snowfall", version.ref = "androidSnowfall" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktorBom" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-client-android = { module = "io.ktor:ktor-client-android" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
play-publisher = { module = "com.github.triplet.gradle:play-publisher", version.ref = "play-publisher" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-core-remoteviews = { module = "androidx.core:core-remoteviews", version.ref = "core-remoteviews" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
bimap = { module = "io.michaelrocks.bimap:bimap", version.ref = "bimap" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
harmony = { module = "com.frybits.harmony:harmony", version.ref = "harmony" }
junit = { module = "junit:junit", version.ref = "junit" }
kumo-core = { module = "io.github.kawaiidango.kumo-android:kumo-core", version.ref = "kumo-core" }
krate-kotlinx = { module = "hu.autsoft:krate-kotlinx", version.ref = "krate" }
krate = { module = "hu.autsoft:krate", version.ref = "krate" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
live-event = { module = "com.github.hadilq:live-event", version.ref = "live-event" }
material = { module = "com.google.android.material:material", version.ref = "material" }
media = { module = "androidx.media:media", version.ref = "media" }
mpAndroidChart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpAndroidChart" }
nestedscrollwebview = { module = "com.telefonica:nestedscrollwebview", version.ref = "nestedscrollwebview" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette-ktx" }
persistentCookieJar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentCookieJar" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review-ktx" }
vertical-stepper-form = { module = "com.ernestoyaquello.stepperform:vertical-stepper-form", version.ref = "vertical-stepper-form" }
benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-transition = { group = "androidx.transition", name = "transition", version.ref = "transition" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
test = { id = "com.android.test", version.ref = "android-application" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
github-release = { id = "com.github.breadmoirai.github-release", version.ref = "github-release" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
play-publisher = { id = "com.github.triplet.play", version.ref = "play-publisher" }

[bundles]


